import pandas as pd
import os
from sklearn.datasets import fetch_california_housing

def load_data():
    data_path = "../data/california.csv"
    if not os.path.exists(data_path):
        raise FileNotFoundError(f"Dataset not found at {data_path}")

    df = pd.read_csv(data_path)
    X = df.drop("MedHouseVal", axis=1).values
    y = df["MedHouseVal"].values
    return X, y


def generate_data():
    os.makedirs("data", exist_ok=True)
    data = fetch_california_housing(as_frame=True)
    df = data.frame
    df.to_csv("data/california.csv", index=False)
    print("✅ california.csv generated by utils.generate_data()")
