name: MLOps CI/CD MAJOR

on:
  push:
    branches:
      - main

jobs:
  test-suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: pytest tests/

  train-and-quantize:
    runs-on: ubuntu-latest
    needs: test-suite
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure data directory
        run: mkdir -p data && cp data/california.csv data/california.csv || echo "Assuming data exists"

      - name: Train model
        run: python src/train.py

      - name: Quantize model
        run: python src/quantize.py

  docker-test:
    runs-on: ubuntu-latest
    needs: train-and-quantize
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t mlops-major-app .

      - name: Run predict.py inside container
        run: docker run --rm -v ${{ github.workspace }}:/app -w /app/src mlops-major-app python predict.py
